# Generated by Django 4.2 on 2023-05-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('min', models.IntegerField(verbose_name='min_value')),
                ('max', models.IntegerField(verbose_name='max_value')),
                ('default_value', models.IntegerField(verbose_name='default_value')),
            ],
        ),
    ]
