# Generated by Django 4.2 on 2023-05-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep1_t', models.IntegerField(default=0, verbose_name='dep1_t')),
                ('dep1_h', models.IntegerField(default=1, verbose_name='dep1_h')),
                ('dep1_a', models.IntegerField(default=1, verbose_name='dep1_a')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
            },
        ),
    ]
