# Generated by Django 4.2 on 2023-05-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_modelsensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsensor',
            name='dep2_a',
            field=models.IntegerField(default=1, verbose_name='dep2_a'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep2_h',
            field=models.IntegerField(default=1, verbose_name='dep2_h'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep2_t',
            field=models.IntegerField(default=0, verbose_name='dep2_t'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep3_a',
            field=models.IntegerField(default=1, verbose_name='dep3_a'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep3_h',
            field=models.IntegerField(default=1, verbose_name='dep3_h'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep3_t',
            field=models.IntegerField(default=0, verbose_name='dep3_t'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep4_a',
            field=models.IntegerField(default=1, verbose_name='dep4_a'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep4_h',
            field=models.IntegerField(default=1, verbose_name='dep4_h'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep4_t',
            field=models.IntegerField(default=0, verbose_name='dep4_t'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep5_a',
            field=models.IntegerField(default=1, verbose_name='dep5_a'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep5_h',
            field=models.IntegerField(default=1, verbose_name='dep5_h'),
        ),
        migrations.AddField(
            model_name='modelsensor',
            name='dep5_t',
            field=models.IntegerField(default=0, verbose_name='dep5_t'),
        ),
    ]
