# Generated by Django 4.2 on 2023-05-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_modelsensor1_department_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelsensor1',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
    ]
