# Generated by Django 4.2 on 2023-05-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_dep_2_user_dep_3_user_dep_4_user_dep_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_permission',
            field=models.CharField(default='N', max_length=3, verbose_name='update_permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dep_1',
            field=models.CharField(default='N', max_length=3, verbose_name='dep_1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dep_2',
            field=models.CharField(default='N', max_length=3, verbose_name='dep_2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dep_3',
            field=models.CharField(default='N', max_length=3, verbose_name='dep_3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dep_4',
            field=models.CharField(default='N', max_length=3, verbose_name='dep_4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dep_5',
            field=models.CharField(default='N', max_length=3, verbose_name='dep_5'),
        ),
    ]
