# Generated by Django 4.2 on 2023-05-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_update_permission_alter_user_dep_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_message',
            field=models.CharField(default='N', max_length=3, verbose_name='send_message'),
        ),
    ]
